<a href="https://colab.research.google.com/github/francisconetodata/portfolio_python/blob/main/desafio_numpy_freecodecamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Calculadora de média, variância e desvio padrão


In [3]:
import numpy as np

In [9]:
a = np.array([[0, 1, 2],
             [5,8,9],
             [77,8,-9]])
a

array([[ 0,  1,  2],
       [ 5,  8,  9],
       [77,  8, -9]])

In [13]:
# Cálculo da média das linhas
a.mean(1)

array([27.33333333,  5.66666667,  0.66666667])

In [14]:
# Cálculo da variância das linhas
a.var(1)

array([6.66666667e-01, 2.88888889e+00, 1.38288889e+03])

In [15]:
# Cálculo do desvio-padrão das linhas
a.std(1)

array([ 0.81649658,  1.69967317, 37.18721405])